steps:
  # install / setup ci
  - name: node:16.14.2
    entrypoint: npm
    args: ['install']
  #
  # Generate the statis site
  #
  - name: node:16.14.2
    entrypoint: npm
    env:
    - 'BCROS_BASE_URL=$_BCROS_BASE_URL'
    - 'AUTH_URL=$_AUTH_URL'
    - 'NAME_REQUEST_URL=$_NAME_REQUEST_URL'
    - 'COLIN_URL=$_COLIN_URL'
    - 'ONESTOP_URL=$_ONESTOP_URL'
    - 'SOCIETIES_URL=$_SOCIETIES_URL'
    - 'PPR_URL=$_PPR_URL'
    - 'WILLS_URL=$_WILLS_URL'
    - 'BCOL_URL=$_BCOL_URL'
    - 'REGISTRY_ACCOUNT_CREATE_URL=$_REGISTRY_ACCOUNT_CREATE_URL'
    - 'KEYCLOAK_CONFIG_PATH=$_KEYCLOAK_CONFIG_PATH'
    - 'AUTH_API_URL=$_AUTH_API_URL'
    - 'STATUS_API_URL=$_STATUS_API_URL'
    - 'ADDRESSCHANGE_URL=$_ADDRESSCHANGE_URL'
    - 'BUSINESS_URL=$_BUSINESS_URL'
    - 'AUTH_LD_CLIENT_ID=$_AUTH_LD_CLIENT_ID'
    - 'RPT_URL=$_RPT_URL'
    - 'BUSINESS_SEARCH_URL=$_BUSINESS_SEARCH_URL'
    - 'BUS_SEARCH_LEARN_MORE=$_BUS_SEARCH_LEARN_MORE'
    - 'SITEMINDER_LOGOUT_URL=$_SITEMINDER_LOGOUT_URL'
    args: ['--openssl-legacy-provider', 'run', 'generate']
  #
  # Deploy to firebase channel, using the PR #
  # store log to /workspace to get the channel URL
  #
  - name: gcr.io/yfthig-dev/firebase
    entrypoint: bash
    args: ['-c', 'firebase hosting:channel:deploy --project=yfthig-dev PR-$_PR_NUMBER > /workspace/firebase-deploy.txt']
  #
  # Update the PR with the temporary URL
  #
  - id: "Update the PR"
    name: gcr.io/cloud-builders/curl
    entrypoint: bash
    args:
      - -c
      - |
        # Read from "/workspace"
        url=`cat /workspace/firebase-deploy.txt| grep 'Channel URL'| cut -c 77-| cut -d ' ' -f 1`
        echo "this is the body:"
        echo '{"body": "Temporary Url for review:'"$url"'"}'
        curl -X POST \
        https://api.github.com/repos/bcgov/bcregistry/issues/$_PR_NUMBER/comments \
        --header "Authorization: Token $$TOKEN" \
        --header "Accept: application/vnd.github.v3+json" \
        --data-binary '{"body": "Temporary Url for review: '"$url"'"}'
    secretEnv: ['TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github-appkey/versions/latest
    env: 'TOKEN'
options:
    dynamic_substitutions: true
